---
title: "R Learning Resources"
author: "by Stuart Hertzog"
date: "March&ndash;May 2018"
---

<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });

    });
</script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> A rich and responsive consellation of print and online information, explanation, guidance, and discussion make up the lively and growing R universe. Help is available at any time --- you just have to know where to find it.

## Books On R

* [Learn R : 12 Free Books and Online Resources](http://ucanalytics.com/blogs/learn-r-12-books-and-online-resources/)
* [Practical Data Science With R](https://www.manning.com/books/practical-data-science-with-r)
* [R in Action, Second Edition](https://www.manning.com/books/r-in-action-second-edition?a_bid=5c2b1e1d&a_aid=RiA2ed)
* [**R For Data Science** by Hadley Wickham](https://www.amazon.com/R-Data-Science-Hadley-Wickham/dp/1491910399/ref=as_li_ss_tl?ie=UTF8&qid=1469550189&sr=8-1&keywords=R+for+data+science&linkCode=sl1&tag=devtools-20&linkId=6fe0069f9605cf847ed96c191f4e84dd)
* [R for Everyone by Jared Lander](https://www.jaredlander.com/r-for-everyone/)
* [Teach Yourself R In 24 Hours](https://www.informit.com/store/r-in-24-hours-sams-teach-yourself-9780672338489)
* [The R Series | CRC Press Online](https://www.crcpress.com/Chapman--HallCRC-The-R-Series/book-series/CRCTHERSER)

### Online R Books
 
* [bookdown: Authoring Books With RMarkdown by Yihui Xie](https://bookdown.org/yihui/bookdown/)
* [bookdown.org: R books made with bookdown](https://bookdown.org/)
* [Data Visualization by Kieran Healy](http://socviz.co/index.html)
* [Efficient R programming by Colin Gillespie &amp;
Robin Lovelace](https://csgillespie.github.io/efficientR/)
* [Happy Git and GitHub for the useR by Jenny Bryan &amp; Others](http://happygitwithr.com/)
* [**R For Data Science** by Hadley Wickham](http://r4ds.had.co.nz/)
* [R packages by Hadley Wickham](http://r-pkgs.had.co.nz/)
* [Text Mining with R by Julia Silge and David Robinson](https://www.tidytextmining.com/)

### WikiBooks on R

* [Data Mining Algorithms In R](https://en.wikibooks.org/wiki/Data_Mining_Algorithms_In_R)
* [R Programming](https://en.wikibooks.org/wiki/R_Programming)
* [Statistical Analysis: an Introduction using R](https://en.wikibooks.org/wiki/Statistical_Analysis:_an_Introduction_using_R)

## R Blogs

### Aggregation Sites

* [**R-bloggers | R news and tutorials by R bloggers**](https://www.r-bloggers.com/)
* [RWeekly.org - Blogs to Learn R from the Community](https://rweekly.org/)
* [Statistics Blogs @ StatsBlogs.com | All About Statistics |](http://www.statsblogs.com/)

### Corporate/NGO 

* [RStudio Blog](https://blog.rstudio.org/)
* [RStudio RViews](https://rviews.rstudio.com/)
* [Revolutions](http://blog.revolutionanalytics.com/)
* [rOpenSci Blog](https://ropensci.org/blog/)

### Personal

* [Jared Lander](https://www.jaredlander.com/)
* [John Myles White](http://www.johnmyleswhite.com/)
* [Andrew Gelman](http://andrewgelman.com/)
* [Learning Slowly](https://jehrlinger.wordpress.com/)
* [TRinker's R Blog](https://trinkerrstuff.wordpress.com/)
* [You Canalytics](http://ucanalytics.com/blogs/)

## R Tutorials

* [Awesome-R: A curated list | GitHub](https://github.com/qinwf/awesome-R)
* [Data Visualization](http://socviz.co/index.html)
* [Getting Started | RStudio Support](https://support.rstudio.com/hc/en-us/sections/200271437-Getting-Started)
* [How to get started with Data Science using R | R-bloggers](https://www.r-bloggers.com/how-to-get-started-with-data-science-using-r/)
* [Implementation of the Matplolib 'viridis' color map in R | GitHub](https://github.com/sjmgarnier/viridis)
* [Learn R, Python & Data Science Online | DataCamp](https://www.datacamp.com/)
* [Quick list of useful R packages | RStudio Support](https://support.rstudio.com/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages)
* [Quick R | DataCamp](https://www.statmethods.net/r-tutorial/index.html)
* [R Package Management Tools](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/packageStatus.html)
* [R-Courses | R-Exercises](https://www.r-exercises.com/r-courses/)
* [Start here to learn R! | R-Exercises](https://www.r-exercises.com/start-here-to-learn-r/)
* [Try R | Code School](http://tryr.codeschool.com/)
* [Tutorials for learning R | R-bloggers](https://www.r-bloggers.com/how-to-learn-r-2/)
* [UBC STAT 545](http://stat545.com/index.html)
* [Using R | Working With Data Series](http://mazamascience.com/WorkingWithData/?series=using-r)

## R Discussion Forums

* [Cross Validated | Newest 'r' Questions](https://stats.stackexchange.com/questions/tagged/r)
* [Stack Overflow | Newest 'r' Questions](https://stackoverflow.com/questions/tagged/r)
* [R Forum | nabble](http://r.789695.n4.nabble.com/)
* [R Learning Resources](http://r.stuzog.com/R_Learning_Resources.html)
* [R Resources for Beginners](http://www.introductoryr.co.uk/R_Resources_for_Beginners.html)
* [R-help Info Page](https://stat.ethz.ch/mailman/listinfo/r-help)
* [R-Help Subscription Page](http://r.789695.n4.nabble.com/mailing_list/MailingListOptions.jtp?forum=789696)

## R Mailing Lists

* [R Project Mailing Lists](https://www.r-project.org/mail.html)
* [R Mailing List Archive](http://r.789695.n4.nabble.com/)
* [R Mailing List Subscription](http://r.789695.n4.nabble.com/template/NamlServlet.jtp?macro=start_registration_page&nextUrl=http%3A%2F%2Fr.789695.n4.nabble.com%2F)
* [R-help | Mailing List Archive](http://r.789695.n4.nabble.com/R-help-f789696.html)
* [R-help | Mailing List Subscription](https://stat.ethz.ch/mailman/listinfo/r-help)

## R Podcasts

If you're into listening to podcasts, there are many great podcasts about R, Data Science, and Artificial Intelligence. Here are some:

- [Not So Standard Deviations](http://nssdeviations.com/)
- [DataFramed](https://www.datacamp.com/community/podcast?tap_a=5644-dce66f&tap_s=10907-287229)
- [The R Podcast](https://r-podcast.org/)
- [This Week in Machine Learning and AI](https://twimlai.com/)
- [The Microsoft Research Podcast](https://www.microsoft.com/en-us/research/blog/category/podcast/)
- [Bombshell](https://warontherocks.com/category/podcasts/bombshell/)
- [Marketplace](https://www.marketplace.org/)
- [Revolutions](http://www.revolutionspodcast.com/)

Collected from: [A few podcast recommendations | R-bloggers](https://www.r-bloggers.com/a-few-podcast-recommendations/)


<hr />

<span class="glyphicon glyphicon-arrow-left"></span> [_Part 2 - Fundamentals of R_](Part2_R_Programming.html) | [_Home_](index.html) <span class="glyphicon glyphicon-arrow-right"></span>

<hr />